---
- name: Prepare for build
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Read users from CSV file and return a list of dictionaries
    read_csv:
      path: switch_list.csv
    register: switches  
  - name: Create build directories
    shell: | 
      mkdir -p tmp/{{item.hostname}}
      touch tmp/{{item.hostname}}/extra-{{item.hostname}}.txt
    loop: "{{ switches.list }}"

- name: Generate configs
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - base
