---
- name: Read switches from CSV file and return a list of dictionaries
  read_csv:
    path: /home/owendev/work/xyz/net4/switch_list.csv
  register: switches
- name: Generate configuration files
  template: src=00-swa-base.j2 dest=/home/owendev/work/xyz/net4/tmp/{{item.hostname}}/00-base-{{item.hostname}}.txt
  loop: "{{ switches.list }}"
